// https://www.geeksforgeeks.org/print-subsequences-string/

// Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

#include <iostream>
using namespace std;
#include <vector>

class Solution
{
    void getSubsequence(string str, vector<string> &output)
    {
        // Base Case--
        if (str.size() == 0)
        {
            return;
        }

        // Form Subsequences--
        int size = output.size(); // As size is always increasing the loop will be infinite..
        string s = "";
        s += str[0];
        output.push_back(s);
        for (int i = 0; i < size; i++)
        {
            s = output[i] + str[0];
            output.push_back(s);
        }

        // Reccursive Call--
        getSubsequence(str.substr(1), output);
        return;
    }

public:
    void printSubsequence(string str)
    {
        vector<string> output;
        getSubsequence(str, output);
        for (int i = 0; i < output.size(); i++)
        {
            cout << output[i] << " ";
        }
        cout << endl;

        return;
    }
};

int main()
{
    string s;
    cin >> s;

    Solution obj;
    obj.printSubsequence(s);

    return 0;
}